const colors={persistence:"#aab7c5","constant-motion":"#e8b44a",ridge:"#bd7aff",gru:"#55d7ff"};
const names={persistence:"Persistence","constant-motion":"Constant Motion",ridge:"Ridge",gru:"GRU"};
const basins={NA:"ATLANTIC",EP:"EAST PACIFIC",WP:"WEST PACIFIC",NI:"NORTH INDIAN",SI:"SOUTH INDIAN",SP:"SOUTH PACIFIC"};
const $=id=>document.getElementById(id),tag=(n,a={})=>"<"+n+" "+Object.entries(a).map(([k,v])=>k+'="'+v+'"').join(" ")+" />",txt=s=>String(s);
let data,borders,state={storm:null,index:0,model:"gru",map:null,drag:null,timer:null};
const stamp=v=>new Date(v).toLocaleString("en-GB",{timeZone:"UTC",month:"short",day:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).replace(",","")+" UTC";
const pos=(v,lat)=>Math.abs(v).toFixed(1)+"°"+(lat?(v>=0?"N":"S"):(v>=0?"E":"W"));
Promise.all([fetch("data/replay.json").then(r=>r.ok?r.json():Promise.reject(Error("Run make frontend-data first."))),fetch("data/countries-110m.json").then(r=>r.ok?r.json():Promise.reject(Error("Missing local geographic boundary data.")))]).then(x=>init(x[0],x[1])).catch(e=>{$("app").textContent=e.message});
function init(payload,world){data=payload;borders=decode(world);$("app").replaceChildren($("ui").content.cloneNode(true));$("app").classList.remove("loading");
 const select=$("stormSelect");data.storms.forEach((s,i)=>select.add(new Option((basins[s.basin]||s.basin)+" "+s.season+" — "+s.name,i)));$("modelSelect").innerHTML=data.models.map(m=>"<option value='"+m+"'>"+names[m]+"</option>").join("");
 select.onchange=()=>{stop();state.storm=data.storms[select.value];state.index=0;fit();render()};$("modelSelect").onchange=e=>{state.model=e.target.value;render()};["showObserved","showActual"].forEach(id=>$(id).onchange=render);
 document.querySelectorAll(".panel-toggle,.panel-edge-control,.edge-tab").forEach(b=>b.onclick=()=>togglePanel(b.dataset.panel));
 $("previous").onclick=()=>move(-1);$("next").onclick=()=>move(1);$("play").onclick=play;$("speed").onchange=()=>{if(state.timer){stop();play()}};$("scrubber").oninput=e=>{state.index=+e.target.value;render()};$("fullCanvas").onclick=()=>document.documentElement.requestFullscreen?.();$("zoomIn").onclick=()=>zoom(1.35);$("zoomOut").onclick=()=>zoom(1/1.35);$("fitMap").onclick=()=>{fit();map()};window.onresize=map;
 state.storm=data.storms[0];fit();render()}
function togglePanel(side){let panel=$(side),closed=panel.classList.toggle("closed"),tab=$(side+"Tab"),app=$("app");tab.classList.toggle("visible",closed);app.classList.toggle(side+"-collapsed",closed);let inner=panel.querySelector(".panel-toggle");if(inner)inner.textContent=side==="left"?"‹":"›";map();window.setTimeout(map,190);}
function point(){return state.storm.observed[state.index]}function leads(){return state.storm.forecasts.filter(f=>f.issueTime===point().time&&f.predictions[state.model])}
function fit(){let p=state.storm.observed,a=Math.min(...p.map(x=>x.lat)),b=Math.max(...p.map(x=>x.lat)),c=Math.min(...p.map(x=>x.lon)),d=Math.max(...p.map(x=>x.lon)),pad=Math.max(2,(b-a)*.22,(d-c)*.18);state.map={a:a-pad,b:b+pad,c:c-pad,d:d+pad,z:1}}
function render(){let p=point(),l=leads(),s=state.storm;$("stormTitle").textContent=(basins[s.basin]||s.basin)+" "+s.season+" — "+s.name;$("stormMeta").textContent="IBTrACS · "+s.stormId;$("position").textContent=pos(p.lat,true)+"  "+pos(p.lon,false);$("wind").textContent=p.wind.toFixed(0)+" kt";$("replayTime").textContent=stamp(p.time);$("forecastCount").textContent=l.length+" VALID LEAD"+(l.length===1?"":"S");$("timelineTime").textContent=stamp(p.time);$("scrubber").max=s.observed.length-1;$("scrubber").value=state.index;$("forecastKeyText").textContent=names[state.model];$("forecastKey").style.background=colors[state.model];$("chartLegendText").textContent=names[state.model];$("chartLegendLine").style.background=colors[state.model];table(l);chart(l);comparison();map()}
function table(l){$("forecastRows").innerHTML=l.length?l.map(f=>{let p=f.predictions[state.model];return '<div class="forecast-row"><button data-h="'+f.horizonHours+'">+'+f.horizonHours+'H</button><span>'+pos(p.lat,true)+" "+pos(p.lon,false)+"</span><span>"+p.wind.toFixed(0)+" kt</span><span class=\"error\">"+p.trackErrorKm.toFixed(0)+" km</span></div>"}).join(""):'<div class="forecast-row"><span>—</span><span>No archived prediction at this timestamp</span><span>—</span><span>—</span></div>';document.querySelectorAll("[data-h]").forEach(b=>b.onmouseenter=e=>tip(e,leads().find(f=>f.horizonHours===+b.dataset.h),true))}
function chart(l){let svg=$("intensity"),w=svg.clientWidth||430,h=svg.clientHeight||155,all=state.storm.observed,max=Math.max(40,...all.map(p=>p.wind),...l.map(f=>f.predictions[state.model].wind))+10,xy=(p,i,n)=>[27+i/(n-1||1)*(w-40),h-20-p.wind/max*(h-40)],path=x=>x.map((p,i)=>(i?"L":"M")+xy(p,i,x.length).join(",")).join(" "),html=tag("path",{class:"chart-grid",d:"M27,"+(h-20)+"H"+(w-13)+" M27,"+(h/2)+"H"+(w-13)+" M27,18H"+(w-13)})+'<text class="chart-text" x="2" y="22">'+max.toFixed(0)+'kt</text><text class="chart-text" x="8" y="'+(h-18)+'">0</text>'+tag("path",{class:"chart-line chart-observed",d:path(all)});
 l.forEach(f=>{let a=xy(point(),0,2),b=xy(f.predictions[state.model],1,2);html+=tag("path",{class:"chart-line chart-prediction",style:"stroke:"+colors[state.model],d:"M"+a+" L"+b})});svg.innerHTML=html}
function comparison(){$("comparison").innerHTML=data.models.map(m=>{let r=data.summary.find(x=>x.model===m&&x.horizon_hours===24);return r?'<div class="comparison-row '+(m===state.model?"active":"")+'"><b>'+names[m]+"</b><span>"+r.track_mean_km.toFixed(1)+" km<br>track mean</span><span>"+r.wind_mae_kt.toFixed(1)+" kt<br>wind MAE</span></div>":""}).join("")}
function map(){let svg=$("map");if(!svg||!state.map)return;let w=svg.clientWidth||1200,h=svg.clientHeight||700,m=state.map,z=m.z,midLon=(m.c+m.d)/2,midLat=(m.a+m.b)/2,lon=(m.d-m.c)/z,lat=(m.b-m.a)/z,xy=p=>[55+(p.lon-(midLon-lon/2))/lon*(w-110),h-42-(p.lat-(midLat-lat/2))/lat*(h-84)],path=x=>x.map((p,i)=>(i?"L":"M")+xy(p).join(",")).join(" "),p=point(),l=leads(),html="";
 for(let x=Math.ceil((midLon-lon/2)/10)*10;x<midLon+lon/2;x+=10){let q=xy({lat:midLat,lon:x})[0];html+=tag("path",{class:"map-grid",d:"M"+q+",20V"+(h-42)})+'<text class="grid-label" x="'+(q+3)+'" y="33">'+Math.abs(x)+"°"+(x<0?"W":"E")+"</text>"}for(let y=Math.ceil((midLat-lat/2)/10)*10;y<midLat+lat/2;y+=10){let q=xy({lat:y,lon:midLon})[1];html+=tag("path",{class:"map-grid",d:"M55,"+q+"H"+(w-55)})+'<text class="grid-label" x="60" y="'+(q-4)+'">'+Math.abs(y)+"°"+(y<0?"S":"N")+"</text>"}
 html+=borders.map(a=>tag("path",{class:"country-border",d:path(a)})).join("")+'<text class="map-label" x="'+(w*.43)+'" y="'+(h*.5)+'">ATLANTIC BASIN</text>';if($("showObserved").checked)html+=tag("path",{class:"track-observed",d:path(state.storm.observed)})+tag("path",{class:"track-past",d:path(state.storm.observed.slice(0,state.index+1))});if($("showActual").checked)l.forEach(f=>html+=tag("path",{class:"actual-path",d:path([p,f.actual])}));l.forEach(f=>{let q=f.predictions[state.model],a=xy(q);html+=tag("path",{class:"forecast-path",style:"stroke:"+colors[state.model],d:path([p,q])})+tag("circle",{class:"forecast-point point","data-h":f.horizonHours,cx:a[0],cy:a[1],r:5,fill:colors[state.model]})});state.storm.observed.forEach((q,i)=>{let a=xy(q);html+=tag("circle",{class:(i===state.index?"current-point":"observed-point")+" point","data-i":i,cx:a[0],cy:a[1],r:i===state.index?7:3.5})});svg.innerHTML=html;
 svg.querySelectorAll("[data-i]").forEach(n=>{n.onclick=()=>{state.index=+n.dataset.i;render()};n.onmouseenter=e=>tip(e,state.storm.observed[+n.dataset.i]);n.onmouseleave=hide});svg.querySelectorAll("[data-h]").forEach(n=>{n.onmouseenter=e=>tip(e,l.find(f=>f.horizonHours===+n.dataset.h),true);n.onmouseleave=hide});svg.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1.25:1/1.25)};svg.onpointerdown=e=>{state.drag={x:e.clientX,y:e.clientY};svg.setPointerCapture(e.pointerId)};svg.onpointermove=e=>{if(!state.drag)return;let dx=e.clientX-state.drag.x,dy=e.clientY-state.drag.y;state.drag={x:e.clientX,y:e.clientY};m.c-=dx/w*lon;m.d-=dx/w*lon;m.a+=dy/h*lat;m.b+=dy/h*lat;map()};svg.onpointerup=()=>state.drag=null}
function zoom(x){state.map.z=Math.max(.6,Math.min(12,state.map.z*x));map()}function decode(t){let s=t.transform?.scale||[1,1],o=t.transform?.translate||[0,0];return t.arcs.map(a=>{let x=0,y=0;return a.map(p=>{x+=p[0];y+=p[1];return{lon:x*s[0]+o[0],lat:y*s[1]+o[1]}})})}
function tip(e,item,forecast=false){let t=$("tooltip");t.hidden=false;if(forecast){let p=item.predictions[state.model];t.innerHTML="<b>+"+item.horizonHours+"H "+names[state.model].toUpperCase()+"</b><br>"+pos(p.lat,true)+" "+pos(p.lon,false)+" / "+p.wind.toFixed(0)+" kt<br>Actual: "+pos(item.actual.lat,true)+" "+pos(item.actual.lon,false)+" / "+item.actual.wind.toFixed(0)+" kt<br>Track error: "+p.trackErrorKm.toFixed(1)+" km"}else t.innerHTML="<b>OBSERVED IBTRACS</b><br>"+stamp(item.time)+"<br>"+pos(item.lat,true)+" "+pos(item.lon,false)+" / "+item.wind.toFixed(0)+" kt";let r=$("map").getBoundingClientRect();t.style.left=Math.min(r.width-275,(e.clientX||r.left)-r.left+14)+"px";t.style.top=Math.max(10,(e.clientY||r.top)-r.top-10)+"px"}function hide(){$("tooltip").hidden=true}function move(n){state.index=(state.index+n+state.storm.observed.length)%state.storm.observed.length;render()}function stop(){clearInterval(state.timer);state.timer=null;$("play")&&($("play").textContent="▶")}function play(){if(state.timer)return stop();$("play").textContent="❚❚";state.timer=setInterval(()=>move(1),+$("speed").value)}
