const $ = id => document.getElementById(id);
const modelNames = {seasonal_naive:"Seasonal naive",arima:"ARIMA",sarima:"SARIMA",holt_winters:"Additive Holt-Winters",xgboost:"XGBoost",lstm:"LSTM",prophet:"Prophet",ensemble_xgboost_prophet:"XGBoost + Prophet ensemble"};
const colors = {seasonal_naive:"#93a4b8",arima:"#ef8f8f",sarima:"#55d7ff",holt_winters:"#b6c2cf",xgboost:"#67dfaa",lstm:"#82dcf3",prophet:"#d0a6ff",ensemble_xgboost_prophet:"#f5c45b"};
let data, selectedModel = "ensemble_xgboost_prophet";

fetch("data/monthly.json").then(r => r.ok ? r.json() : Promise.reject(Error("Run make monthly-frontend-data first."))).then(init).catch(error => {$("monthlyApp").innerHTML = `<div class="error">${error.message}</div>`});

function init(payload) {
  data = payload;
  $("monthlyApp").innerHTML = `
    <header class="labbar"><a class="brand" href="index.html"><span class="brand-mark">◉</span> TROP-CYC <span>/</span> RESEARCH LAB</a><span class="lab-divider"></span><span class="page-tag">MONTHLY ACTIVITY</span><a class="back-link" href="index.html">Spatial Trajectory ↗</a></header>
    <section class="intro"><div><p class="eyebrow">NORTH ATLANTIC / IBTRACS V04R01</p><h1>Monthly storm activity</h1><p class="lede">A chronological experiment forecasting the monthly count of retained North Atlantic storms. Each retained SID is counted once, in the month of its first retained six-hour observation.</p></div><div class="intro-meta"><span>1980–2025</span><span>ONE-STEP AHEAD</span><span>ZERO MONTHS RETAINED</span></div></section>
    <section class="hero panel"><div class="panel-head"><div><p class="eyebrow">ACTIVITY SERIES / FORECAST WINDOW</p><h2>Observed monthly counts and model forecasts</h2></div><label class="model-control">VIEW MODEL<select id="modelSelect"></select></label></div><div class="legend"><span><i class="swatch actual"></i>Observed</span><span><i class="swatch forecast"></i><b id="legendModel">Ensemble</b> forecast</span><span class="boundary-key"><i></i>Test boundary · Jan 2020</span></div><svg id="mainChart" class="main-chart" role="img" aria-label="Monthly storm count series and forecast"></svg><div class="chart-note">Forecasts share the same validation and test timestamps. The shaded region begins with the held-out 2020–2025 test period.</div></section>
    <section class="analysis-grid"><article class="panel season-panel"><div class="panel-head compact"><div><p class="eyebrow">SEASONAL PROFILE</p><h2>Month-of-year activity</h2></div><span class="quiet">Observed series</span></div><svg id="seasonChart" class="season-chart" role="img" aria-label="Mean storm count by calendar month"></svg><p class="body-copy">Seasonality is descriptive: values are the observed mean count for each calendar month across 1980–2025.</p></article><article class="panel decomposition-panel"><div class="panel-head compact"><div><p class="eyebrow">DECOMPOSITION</p><h2>Trend, seasonal component, residual</h2></div><span class="quiet">Period 12</span></div><svg id="decompChart" class="decomp-chart" role="img" aria-label="Monthly decomposition"></svg><div class="component-key"><span><i class="trend"></i>Trend</span><span><i class="seasonal"></i>Seasonal</span><span><i class="residual"></i>Residual</span></div></article></section>
    <section class="panel benchmark"><div class="panel-head compact"><div><p class="eyebrow">HELD-OUT BENCHMARK</p><h2>Test-period model comparison</h2></div><span class="quiet">2020–2025 · 72 months</span></div><div id="metricsTable" class="metrics-table"></div></section>
    <section class="method-strip"><div><p class="eyebrow">PROTOCOL</p><h2>Chronological, validation-only selection</h2></div><div class="method-item"><b>TRAIN</b><span>1980–2015</span></div><div class="method-item"><b>VALIDATION</b><span>2016–2019</span></div><div class="method-item"><b>TEST</b><span>2020–2025</span></div><div class="method-copy">Expanding-window one-step forecasts. MAE, RMSE, and MASE use the same monthly timestamps and training scale. No random splits or test-set tuning.</div></section>
    <footer><span>STATIC RESEARCH PRESENTATION / NON-OPERATIONAL</span><span>Source: ${data.source}</span></footer>`;
  const select = $("modelSelect"); Object.entries(data.models).forEach(([key,name]) => select.add(new Option(name,key))); select.value=selectedModel; select.onchange=e=>{selectedModel=e.target.value; render()}; const tip=document.createElement("div"); tip.id="chartTooltip"; tip.className="chart-tooltip"; tip.hidden=true; $("mainChart").parentElement.append(tip); window.addEventListener("resize",render); render();
}

function render(){ $("legendModel").textContent=modelNames[selectedModel]; drawMain(); drawSeason(); drawDecomp(); drawMetrics(); }
function extent(values){let lo=Math.min(...values),hi=Math.max(...values);if(hi===lo)hi=lo+1;return [lo,hi]}
function path(points,width,height,pad,min,max,xfn){return points.map((v,i)=>`${i?"L":"M"}${xfn(i)},${height-pad-(v-min)/(max-min)*(height-2*pad)}`).join(" ")}
function svgText(x,y,text,cls="axis-label"){return `<text x="${x}" y="${y}" class="${cls}">${text}</text>`}
function monthLabel(value){return new Date(value).toLocaleString("en-US",{month:"short",year:"numeric",timeZone:"UTC"})}
function rowForMonth(rows,month){return rows.find(row=>row.month===month)}
function showTip(event,html){let tip=$("chartTooltip");tip.innerHTML=html;tip.hidden=false;tip.style.left=Math.max(8,event.clientX+14)+"px";tip.style.top=Math.max(8,event.clientY-18)+"px"}
function hideTip(){if($("chartTooltip"))$("chartTooltip").hidden=true}
function bindMainHover(svg,ctx){let cross=document.createElementNS("http://www.w3.org/2000/svg","g");cross.innerHTML='<line class="hover-cross"/><circle class="hover-actual"/><circle class="hover-forecast"/>';svg.append(cross);let hit=document.createElementNS("http://www.w3.org/2000/svg","rect");hit.setAttribute("class","chart-hit");hit.setAttribute("x",ctx.pad.l);hit.setAttribute("y",ctx.pad.t);hit.setAttribute("width",ctx.w-ctx.pad.l-ctx.pad.r);hit.setAttribute("height",ctx.h-ctx.pad.t-ctx.pad.b);svg.append(hit);hit.onpointermove=e=>{let r=svg.getBoundingClientRect(),px=e.clientX-r.left,i=Math.max(0,Math.min(ctx.series.length-1,Math.round(ctx.indexAt(px)))),row=ctx.seriesRows[i],actual=+ctx.series[i].storm_count,fx=ctx.x(i),ay=ctx.y(actual);cross.querySelector(".hover-cross").setAttribute("x1",fx);cross.querySelector(".hover-cross").setAttribute("x2",fx);cross.querySelector(".hover-cross").setAttribute("y1",ctx.pad.t);cross.querySelector(".hover-cross").setAttribute("y2",ctx.h-ctx.pad.b);cross.querySelector(".hover-actual").setAttribute("cx",fx);cross.querySelector(".hover-actual").setAttribute("cy",ay);let forecast=row&&Number.isFinite(+row.forecast)?+row.forecast:null;cross.querySelector(".hover-forecast").setAttribute("cx",fx);cross.querySelector(".hover-forecast").setAttribute("cy",forecast===null?ay:ctx.y(forecast));cross.querySelector(".hover-forecast").style.display=forecast===null?"none":"block";showTip(e,`<b>${monthLabel(ctx.series[i].month)}</b><br>Observed: ${actual.toFixed(0)} storms${forecast===null?"":`<br>${modelNames[selectedModel]}: ${forecast.toFixed(3)}`}`,svg.parentElement)};hit.onpointerleave=()=>{cross.style.display="none";hideTip()};hit.onpointerenter=()=>cross.style.display="block"}
function drawMain(){let svg=$("mainChart"),w=svg.clientWidth||1100,h=svg.clientHeight||370,series=data.series,rows=data.forecasts[selectedModel].filter(row=>row.model===selectedModel),forecast=rows.map(x=>+x.forecast),all=series.map(x=>+x.storm_count).concat(forecast),[min,max]=extent(all),pad={l:42,r:20,t:18,b:31},testIndex=series.findIndex(x=>x.month.startsWith("2020-01")),testX=pad.l+(w-pad.l-pad.r)*.31,x=i=>i<testIndex?pad.l+(testX-pad.l)*i/testIndex:testX+(w-pad.r-testX)*(i-testIndex)/(series.length-1-testIndex),y=v=>h-pad.b-(v-min)/(max-min)*(h-pad.t-pad.b),html="";for(let i=0;i<5;i++){let value=min+(max-min)*i/4,yy=y(value);html+=`<line class="grid-line" x1="${pad.l}" x2="${w-pad.r}" y1="${yy}" y2="${yy}"/>${svgText(5,yy+4,value.toFixed(0))}`};html+=`<rect class="history-band" x="${pad.l}" y="${pad.t}" width="${testX-pad.l}" height="${h-pad.t-pad.b}"/><rect class="test-band" x="${testX}" y="${pad.t}" width="${w-pad.r-testX}" height="${h-pad.t-pad.b}"/><line class="test-line" x1="${testX}" x2="${testX}" y1="${pad.t}" y2="${h-pad.b}"/>${svgText(testX+8,pad.t+14,"TEST · 2020–2025","boundary-label")}${svgText(pad.l+8,pad.t+14,"HISTORY · 1980–2019","history-label")}`;html+=`<path class="actual-path" d="${path(series.map(x=>+x.storm_count),w,h,pad.l,min,max,x)}"/>`;let points=rows.map(row=>({...row,index:series.findIndex(x=>x.month===row.month)})).filter(row=>row.index>=0);if(points.length){html+=`<path class="forecast-path" style="stroke:${colors[selectedModel]}" d="${points.map((row,i)=>`${i?"L":"M"}${x(row.index)},${y(+row.forecast)}`).join(" ")}"/>`};for(let year=1980;year<=2025;year+=5){let i=series.findIndex(v=>v.month.startsWith(`${year}-01`));if(i>=0)html+=svgText(x(i)-15,h-8,year)}svg.innerHTML=html;bindMainHover(svg,{w,h,pad,series,seriesRows:series.map(item=>rowForMonth(rows,item.month)),x,y,indexAt:px=>{if(px<=testX)return (px-pad.l)/(testX-pad.l)*testIndex;return testIndex+(px-testX)/(w-pad.r-testX)*(series.length-1-testIndex)}})}
function drawSeason(){let svg=$("seasonChart"),w=svg.clientWidth||580,h=svg.clientHeight||235,monthly=Array.from({length:12},(_,m)=>{let a=data.series.filter(x=>new Date(x.month).getUTCMonth()===m);return a.reduce((s,x)=>s+ +x.storm_count,0)/a.length}),[min,max]=extent(monthly),pad={l:34,r:16,t:18,b:32},bar=(w-pad.l-pad.r)/12,html="";for(let i=0;i<4;i++){let v=max*i/3,yy=h-pad.b-(v/max)*(h-pad.t-pad.b);html+=`<line class="grid-line" x1="${pad.l}" x2="${w-pad.r}" y1="${yy}" y2="${yy}"/>${svgText(2,yy+4,v.toFixed(1))}`};monthly.forEach((v,i)=>{let bh=v/max*(h-pad.t-pad.b),x=pad.l+i*bar+bar*.14,y=h-pad.b-bh,month=new Date(Date.UTC(2000,i,1)).toLocaleString("en-US",{month:"short",timeZone:"UTC"});html+=`<rect class="season-bar ${i>=6&&i<=9?"peak":""}" data-month="${month}" data-value="${v}" x="${x}" y="${y}" width="${bar*.72}" height="${bh}"/><text class="axis-label" x="${x+bar*.36}" y="${h-10}" text-anchor="middle">${month}</text>`});svg.innerHTML=html;svg.querySelectorAll(".season-bar").forEach(bar=>{bar.onpointerenter=e=>{bar.classList.add("hovered");showTip(e,`<b>${bar.dataset.month}</b><br>Mean count: ${(+bar.dataset.value).toFixed(3)} storms`,svg.parentElement)};bar.onpointerleave=()=>{bar.classList.remove("hovered");hideTip()}})}
function drawDecomp(){let svg=$("decompChart"),w=svg.clientWidth||580,h=svg.clientHeight||235,rows=data.decomposition,sets=[{key:"trend",cls:"trend-path"},{key:"seasonal",cls:"seasonal-path"},{key:"residual",cls:"residual-path"}],values=sets.flatMap(s=>rows.map(x=>+x[s.key]).filter(Number.isFinite)),[min,max]=extent(values),pad=32,html="";for(let i=0;i<3;i++){let yy=pad+i*(h-2*pad)/2;html+=`<line class="grid-line" x1="${pad}" x2="${w-pad}" y1="${yy}" y2="${yy}"/>`};sets.forEach(s=>{let vals=rows.map(x=>Number.isFinite(+x[s.key])?+x[s.key]:0);html+=`<path class="${s.cls}" d="${path(vals,w,h,pad,min,max,i=>pad+i*(w-2*pad)/(rows.length-1))}"/>`});let hit=document.createElementNS("http://www.w3.org/2000/svg","rect");svg.innerHTML=html;hit.setAttribute("class","chart-hit");hit.setAttribute("x",pad);hit.setAttribute("y",0);hit.setAttribute("width",w-2*pad);hit.setAttribute("height",h);svg.append(hit);hit.onpointermove=e=>{let r=svg.getBoundingClientRect(),i=Math.max(0,Math.min(rows.length-1,Math.round((e.clientX-r.left-pad)/(w-2*pad)*(rows.length-1)))),row=rows[i];showTip(e,`<b>${monthLabel(row.month)}</b><br>Trend: ${finite(row.trend)}<br>Seasonal: ${finite(row.seasonal)}<br>Residual: ${finite(row.residual)}`,svg.parentElement)};hit.onpointerleave=hideTip}
function finite(value){return Number.isFinite(+value)?(+value).toFixed(3):"not available"}
function drawMetrics(){let order=["seasonal_naive","arima","sarima","holt_winters","xgboost","lstm","prophet","ensemble_xgboost_prophet"],rows=order.map(model=>data.metrics.find(x=>x.model===model&&x.split==="test")).filter(Boolean);$("metricsTable").innerHTML=`<div class="metric-head"><span>MODEL</span><span>MAE</span><span>RMSE</span><span>MASE</span></div>`+rows.map(row=>`<div class="metric-row ${row.model===selectedModel?"selected":""}" data-model="${row.model}"><b><i style="background:${colors[row.model]||"#9aa9b8"}"></i>${modelNames[row.model]||row.model}</b><span>${finite(row.mae)}</span><span>${finite(row.rmse)}</span><span>${finite(row.mase)}</span></div>`).join("");document.querySelectorAll(".metric-row").forEach(row=>{row.onmouseenter=e=>{row.classList.add("hovered");let metric=rows.find(item=>item.model===row.dataset.model);showTip(e,`<b>${modelNames[metric.model]}</b><br>MAE: ${finite(metric.mae)}<br>RMSE: ${finite(metric.rmse)}<br>MASE: ${finite(metric.mase)}`)};row.onmouseleave=()=>{row.classList.remove("hovered");hideTip()};row.onclick=()=>{selectedModel=row.dataset.model;$("modelSelect").value=selectedModel;render()}})}
